# Generated by Django 5.0.3 on 2024-03-31 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='complete_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='время выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='периодичность(в днях)'),
        ),
    ]
